{
  "formatVersion": "1.1",
  "component": {
    "group": "com.picup.sdk",
    "module": "core_v3",
    "version": "5.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "EnvProdVariantEnvProdApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core_v3-5.0.3.aar",
          "url": "core_v3-5.0.3.aar",
          "size": 1676799,
          "sha512": "37ada59bf977ac29b6ae583cec2f584cf32165b39ccca26363c0fea41f739ccee67984184253d5e324df141eaa4eed105f3270338b0c8cfc14a3519a2df34a06",
          "sha256": "4c9c28126d6026b2da9fe92682c5e512d4f9873d6b058ee4732ba2493dd1c8fd",
          "sha1": "cec1f69a9a961a246e2043e6d1eccc442946deb1",
          "md5": "ee5b2abfbc0de76e258a8a19d6492d82"
        }
      ]
    },
    {
      "name": "EnvProdVariantEnvProdRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v13",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.mixpanel.android",
          "module": "mixpanel-android",
          "version": {
            "requires": "5.8.7"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.14.9"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.12.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "23.1.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-gcm",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.castorflex.smoothprogressbar",
          "module": "library-circular",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.conscrypt",
          "module": "conscrypt-android",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "core_v3-5.0.3.aar",
          "url": "core_v3-5.0.3.aar",
          "size": 1676799,
          "sha512": "37ada59bf977ac29b6ae583cec2f584cf32165b39ccca26363c0fea41f739ccee67984184253d5e324df141eaa4eed105f3270338b0c8cfc14a3519a2df34a06",
          "sha256": "4c9c28126d6026b2da9fe92682c5e512d4f9873d6b058ee4732ba2493dd1c8fd",
          "sha1": "cec1f69a9a961a246e2043e6d1eccc442946deb1",
          "md5": "ee5b2abfbc0de76e258a8a19d6492d82"
        }
      ]
    }
  ]
}
